import type { Metadata } from "next";
import { IBM_Plex_Sans, Fraunces } from "next/font/google";
import "./styles/theme.css";
import "./styles/globals.css";
import Navbar from "./components/layouts/Navbar";
import NavigationMenu from "./components/layouts/NavigationMenu";
import Footer from "./components/layouts/Footer";

const ibmPlexSans = IBM_Plex_Sans({
  variable: "--font-body",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const fraunces = Fraunces({
  variable: "--font-heading",
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ibmPlexSans.variable} ${fraunces.variable} font-body antialiased`}
      >
        <div className="h-[106px]">
          <Navbar />
          <NavigationMenu />
        </div>
        <main className="">
          {children}
          <div className="">
            <Footer />
          </div>
        </main>
      </body>
    </html>
  );
}
